// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pptpddirlsufupdwunsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdHBkZGlybHN1ZnVwZHd1bnNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDQyNjMsImV4cCI6MjA3MDA4MDI2M30.1K2t9ldSnveG-UDmkv1k-7t0XWedxnmp3sDG2DJycGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});